### ISSUE TITLE
New Xiegu Firmware 1.1.8 20240906

### ISSUE THREAD

**Issue by xes** [j0ju/x6100-fw-mangler#2]
https://www.radioddity.com/blogs/all/xiegu-x6100-firmware-upgrade?utm_medium=sidenav&utm_source=product_page&utm_campaign=Product_to_Blog&utm_content=

**Comment by j0ju** [comment]
As always patches are welcome, I have merged now code to use 
`2024-09-23_X6100_APP_V1.1.9_Sep_14_2024_12.11.57_-_BASE_V1.1.8_Sep_15_2024_15.22.37.zip` as a base.
